- name: Create directory
  file: state=directory dest={{ tomcat.home }}

- name: Unarchive tomcat
  unarchive: src=files/esgftomcat.zip dest={{ tomcat.home }}

- name: Install ESGF server.xml
  template: src=server.xml.j2 dest={{ tomcat.home }}/conf/server.xml

- name: Template tomcat-users.xml
  template: src=tomcat-users.xml.j2 dest={{ tomcat.home }}/conf/tomcat-users.xml

- name: Template ORP security-context-auth.xml.j2
  template: src=security-context-auth.xml.j2 dest={{ tomcat.home }}/webapps/esg-orp/WEB-INF/classes/esg/orp/orp/config/security-context-auth.xml

- name: Template ORP security-context-authz.xml.j2
  template: src=security-context-authz.xml.j2 dest={{ tomcat.home }}/webapps/esg-orp/WEB-INF/classes/esg/orp/orp/config/security-context-authz.xml

- name: Template ORP properties
  template: src=esg-orp.properties.j2 dest={{ tomcat.home }}/webapps/esg-orp/WEB-INF/classes/esg-orp.properties

- name: Disable cookie session in ORP
  lineinfile:
    line: "<session-config><tracking-mode>COOKIE</tracking-mode></session-config>"
    dest: "{{ tomcat.home }}/webapps/esg-orp/WEB-INF/web.xml"
    insertbefore: "</web-app>"

- name: Template TDS web.xml
  template: src=web.xml.j2 dest={{ tomcat.home }}/webapps/thredds/WEB-INF/web.xml

- name: Template setenv.sh
  template: src=setenv.sh.j2 dest={{ tomcat.home }}/bin/setenv.sh

- name: Template esg-search my-client-application-context.xml
  template: src=my-client-application-context.xml.j2 dest={{ tomcat.home }}/webapps/esg-search/WEB-INF/classes/esg/search/config/my-client-application-context.xml

- name: Template esg-search application-context.xml
  template: src=application-context.xml.j2 dest={{ tomcat.home }}/webapps/esg-search/WEB-INF/classes/esg/search/config/application-context.xml

- name: Template esg-search application-plugins.xml
  template: src=application-plugins.xml.j2 dest={{ tomcat.home }}/webapps/esg-search/WEB-INF/classes/esg/search/config/application-plugins.xml

- name: Template esg-search app
  template: src=application-plugins.xml.j2 dest={{ tomcat.home }}/webapps/esg-search/WEB-INF/classes/esg/search/config/application-plugins.xml

- name: Template esgf-idp application-config.xml
  template: src=application-config.xml.j2 dest={{ tomcat.home }}/webapps/esgf-idp/WEB-INF/classes/esg/idp/config/application-config.xml

- name: Template esgf-idp yadis-config.xml
  template: src=yadis-config.xml.j2 dest={{ tomcat.home }}/webapps/esgf-idp/WEB-INF/classes/esg/idp/config/yadis-config.xml

- name: Template esgf-idp idp-config.xml
  template: src=idp-config.xml.j2 dest={{ tomcat.home }}/webapps/esgf-idp/WEB-INF/classes/esg/idp/config/idp-config.xml
