- name: Template setenv.sh
  template: src=templates/setenv.sh.j2 dest={{ tomcat.home }}/bin/setenv.sh

- name: Template server.xml
  template: src=templates/server.xml.j2 dest={{ tomcat.home }}/conf/server.xml
  vars:
    shutdown: "{{ tomcat.shutdown }}"
    http: "{{ tomcat.http }}"
    ajp: "{{ tomcat.ajp }}"

- name: Create content/thredds
  file: state=directory path={{ tomcat.home }}/content/thredds

- name: Copy threddsConfig.xml
  copy: src=files/threddsConfig.xml dest={{ tomcat.home }}/content/thredds/threddsConfig.xml
