- name: Template setenv.sh
  template: src=templates/setenv.sh.j2 dest={{ tomcat_home }}/bin/setenv.sh

- name: Template server.xml
  template: src=templates/server.xml.j2 dest={{ tomcat_home }}/conf/server.xml

- name: Create content/thredds
  file: state=directory path={{ tomcat_home }}/content/thredds

- name: Copy threddsConfig.xml
  copy: src=files/threddsConfig.xml dest={{ tomcat_home }}/content/thredds/threddsConfig.xml

#
#- name: Add catalogRef
#  lineinfile:
#    path: "{{ catalog }}"
#    insertbefore: </catalog>
#    line: '<catalogRef xlink:title="{{ id }}" xlink:href="{{ id }}/catalog.xml" name="" />'
