- name: Provision lxc containers
  hosts: all
  become: True
  vars:
    users: [root, ansible]
    key: "/home/{{ lookup('env', 'USER') }}/.ssh/id_rsa.pub"
    debug: True
  tasks:
    # Install packages
    - name: Install Base packages
      yum: name="@Base" state=present
      when: ansible_pkg_mgr == "yum"

    - name: EPEL
      yum: name=epel-release
      when: ansible_pkg_mgr == "yum"

    - name: Required packages
      package: name={{ item }} state=present
      with_items: [openssh-server, sudo, python-passlib, subversion, git]

    - name: Debug packages
      package: name={{ item }} state=present
      with_items: [vim, telnet, net-tools, fuse-sshfs]
      when: debug

    - name: Create users
      user: name={{ item }} shell=/bin/bash
      with_items: "{{ users }}"

    # Allow ssh access
    - name: Copy public key
      authorized_key: user={{ item }} key={{ lookup('file', key) }}
      with_items: "{{ users }}"

    - name: Start sshd
      service: name=sshd state=started
