- name: Create directories for tds
  file: state=directory path={{ tds_home }}

- name: Unarchive TDS
  unarchive: src={{ tds_war }} dest={{ tds_home }}

- name: Update context path in web.xml
  replace:
    path: "{{ tds_home }}/WEB-INF/web.xml"
    regexp: <param-value>thredds</param-value>
    replace: <param-value>{{ tds_context }}</param-value>

- name: Update tds.properties
  replace:
    path: "{{ tds_home }}/WEB-INF/classes/thredds/server/tds.properties"
    regexp: tds.content.path=thredds
    replace: tds.content.path={{ tds_content_path }}

- name: Configure TDS authorizer useSSL
  replace:
    path: "{{ tds_home }}/WEB-INF/applicationContext.xml"
    regexp: <property name="useSSL" value=".*"/>
    replace: <property name="useSSL" value="{{ tds_useSSL }}"/>

- name: Configure TDS authorizer sslPort
  replace:
    path: "{{ tds_home }}/WEB-INF/applicationContext.xml"
    regexp: <property name="sslPort" value=".*"/>
    replace: <property name="sslPort" value="{{ tds_sslPort }}"/>