- name: All servers workers
  hosts: servers
  serial: 1 # multiple hosts writing to the gateway
  vars_files:
    - secrets.yml
  tasks:
    - name: Install workers
      include_role:
        name: udg
      vars:
        udg_home: "{{ worker.home }}"
        udg_jdk: "{{ worker.jdk }}"
        udg_http: "{{ worker.http }}"
        udg_ssl: "{{ worker.ssl }}"
        udg_ajp: "{{ worker.ajp }}"
        udg_shutdown: "{{ worker.shutdown }}"
        udg_derby_name: "{{ worker.derby_name }}"
        udg_derby_user: "{{ worker.derby_user }}"
        udg_derby_password: "{{ worker.derby_password }}"
        udg_derby_url: "{{ worker.derby_url }}"
        udg_ajp_address: "{{ worker.ajp_address }}"
        udg_Xmx: "4096m"
      with_items: "{{ workers }}"
      loop_control:
        loop_var: worker

- name: Restart gateway
  hosts: tdsifca
  tasks:
    - name: Graceful restart
      command: service apache2 graceful
