- name: Provision lxc lbs
  hosts: lb
  become: True
  vars:
    users: [root, ansible]
    key: ../../../insecure_private_key.pub
    debug: True
    hostkey_src: /etc/certs/hostkey.pem
    hostcert_src: /etc/certs/hostcert.pem
    cachain_src: /etc/certs/cachain.pem
  tasks:
    # Install packages
    - name: Install Base packages
      yum: name="@Base" state=present
      when: ansible_pkg_mgr == "yum"

    - name: EPEL
      yum: name=epel-release
      when: ansible_pkg_mgr == "yum"

    - name: Required packages
      package: name={{ item }} state=present
      with_items: [openssh-server, sudo, python-passlib, subversion, git, unzip, mod_geoip]

    - name: Debug packages
      package: name={{ item }} state=present
      with_items: [vim, telnet, net-tools, fuse-sshfs]
      when: debug

    - name: Create users
      user: name={{ item }} shell=/bin/bash
      with_items: "{{ users }}"

    # Allow ssh access
    - name: Copy public key
      authorized_key: user={{ item }} key={{ lookup('file', key) }}
      with_items: "{{ users }}"

    - name: Start sshd
      service: name=sshd state=started

    - name: Create /etc/certs
      file: state=directory path=/etc/certs

    - name: Copy hostkey
      copy: src=../../../insecure_private_key dest={{ hostkey_src }} mode=0400

    - name: Copy hostcert
      copy: src=../../../server.pem dest={{ hostcert_src }} mode=0644

    - name: Copy cachain
      copy: src=../../../server.pem dest={{ cachain_src }} mode=0644
