- name: Provision lxc servers
  hosts: servers
  become: True
  vars:
    users: [root, ansible]
    key: ../../../insecure_private_key.pub
    debug: True
  tasks:
    - name: Set hostname
      command: hostname {{ inventory_hostname }}

    - name: EPEL
      yum: name=epel-release
      when: ansible_pkg_mgr == "yum"

    - name: Required packages
      package: name={{ item }} state=present
      with_items: [openssh-server, sudo, python-passlib, subversion, git, unzip, netcdf]

    - name: Debug packages
      package: name={{ item }} state=present
      with_items: [vim, telnet, net-tools, fuse-sshfs]
      when: debug

    - name: Create users
      user: name={{ item }} shell=/bin/bash
      with_items: "{{ users }}"

    # Allow ssh access
    - name: Copy public key
      authorized_key: user={{ item }} key={{ lookup('file', key) }}
      with_items: "{{ users }}"

    - name: Start sshd
      service: name=sshd state=started

    - name: Create /oceano directory
      file: state=directory path=/oceano user={{ ansible_user }} group={{ ansible_user }} mode=775
