- name: Stop database
  hosts: databases
  tasks:
    - command: bin/stopNetworkServer
      args:
        chdir: "{{ derby_home }}"
      environment:
        DERBY_HOME: "{{ derby_home }}"
        JAVA_HOME: "{{ jdk_home }}"
      ignore_errors: True
