- name: Start httpd
  hosts: lbs
  tasks:
    - name: Start ntpd
      service: name=ntpd state=stopped

    - name: Start filebeat
      service: name=filebeat state=stopped

    - name: Start httpd
      service: name=httpd state=stopped

    - name: Start CoG
      command: /etc/cog-wsgi-8889/apachectl stop
