- name: Stop gateway services
  hosts: lbs
  tasks:
    - name: Stop ntpd
      service: name=ntpd state=stopped

    - name: Stop filebeat
      service: name=filebeat state=stopped

    - name: Stop httpd
      service: name=httpd state=stopped

    - name: Start CoG
      command: /etc/cog-wsgi-8889/apachectl stop
