- name: Stop tomcats
  hosts: servers
  tasks:
    - name: Stop tomcat
      command: "{{ tomcats[item].home }}/bin/shutdown.sh"
      args:
        removes: "{{ tomcats[item].home }}/logs/catalina.pid"
      environment:
        CATALINA_BASE: "{{ tomcats[item].home }}"
      ignore_errors: True # If catalina.pid is present but process is not running, we don't want an error
      with_items: [ "udg", "tds5" ]
    
    - name: Remove catalina.pid
      file: path={{ tomcats[item].home }}/logs/catalina.pid state=absent
      with_items: [ "udg", "tds5" ]
