- name: Stop tomcats
  hosts: servers
  vars_files:
    - ../secrets.yml
  tasks:
    - name: Stop tomcat
      command: "{{ item.home }}/bin/shutdown.sh"
      args:
        removes: "{{ item.home }}/logs/catalina.pid"
      environment:
        CATALINA_BASE: "{{ item.home }}"
      ignore_errors: True # If catalina.pid is present but process is not running, we don't want an error
      with_items:
        - "{{ udg }}"
    
    - name: Remove catalina.pid
      file: path={{ item.home }}/logs/catalina.pid state=absent
      with_items:
        - "{{ udg }}"
