- name: Install devel TDS C3S_34d
  hosts: wn023
  roles:
    - role: devel
      tomcat: "{{ devels.c3s34d }}"
  tasks:
    - name: Start tomcat
      include_tasks:
        file: ../restart.yml
        apply:
          tags: start
      vars:
        tomcat: "{{ devels.c3s34d }}"
      tags: start
