- name: Install devel TDS CORDEX-ESDM
  hosts: wn023
  roles:
    - role: devel
      tomcat: "{{ devels.cordex_esdm }}"
  tasks:
    - name: Start tomcat
      include_tasks:
        file: ../restart.yml
        apply:
          tags: start
      vars:
        tomcat: "{{ devels.cordex_esdm }}"
      tags: start
