- name: Install devel TDS tds5_data
  hosts: wn025
  vars_files:
    - ../secrets.yml
  roles:
    - role: devel
      tomcat: "{{ devels.tds5_data }}"
      tds_context: tds5
  tasks:
    - name: Template server.xml for tds5-data
      template:
        src: templates/tds5-data.server.xml.j2
        dest: "{{ devels.tds5_data.home }}/conf/server.xml"

    - name: Worker for /tds5
      delegate_to: lb
      delegate_facts: true
      blockinfile:
        path: /etc/httpd/conf/httpd.conf
        insertbefore: '<VirtualHost \*:80>'
        block: |
          <Location /tds5>
            ProxyPass ajp://{{ ansible_all_ipv4_addresses[0] }}:{{ devels.tds5_data.ajp }}/tds5
            ProxyPassReverse ajp://{{ ansible_all_ipv4_addresses[0] }}:{{ devels.tds5_data.ajp }}/tds5
          </Location>

    - name: Unarchive derbydb client in tds5-data
      unarchive:
        src: "../{{ derby_tgz }}"
        dest: "{{ devels.tds5_data.home }}/lib"
        exclude:
          - derby.war
          - README.htm
        extra_opts:
          - --strip-components=2

    - name: Start tomcat
      include_tasks:
        file: ../restart.yml
        apply:
          tags: start
      vars:
        tomcat: "{{ devels.tds5_data }}"
      tags: start
