- name: Install devel TDS tds5_data
  hosts: wn025
  vars_files:
    - ../secrets.yml
  roles:
    - role: devel
      tomcat: "{{ tomcats.tds5_data }}"
      tds_context: tds5
  tasks:
    - name: Template server.xml for tds5-data
      template:
        src: templates/tds5-data.server.xml.j2
        dest: "{{ tomcats.tds5_data.home }}/conf/server.xml"

    - name: Unarchive derbydb client in tds5-data
      unarchive:
        src: "../{{ derby_tgz }}"
        dest: "{{ tomcats.tds5_data.home }}/lib"
        exclude:
          - derby.war
          - README.htm
        extra_opts:
          - --strip-components=2

    - name: Copy grib table
      copy: src=tds5/2.98.128.table dest={{ tomcats.tds5_data.home }}/content/thredds/2.98.128.table

    - name: Add grib table to threddsConfig.xml
      blockinfile:
        path: "{{ tomcats.tds5_data.home }}/content/thredds/threddsConfig.xml"
        insertbefore: '</threddsConfig>'
        block: |
          <nj22Config>
            <gribParameterTable edition="1" center="98" subcenter="-1" version="128">{{ tomcats.tds5_data.home }}/content/thredds/2.98.128.table</gribParameterTable>
          </nj22Config>

    - name: Start tomcat
      include_tasks:
        file: ../restart.yml
        apply:
          tags: start
      vars:
        tomcat: "{{ tomcats.tds5_data }}"
      tags: start
