- name: Install local TDS
  hosts: localhost
  vars:
    jdk_tgz: ../../software/jdk8.tar.gz
    tomcat_tgz: ../../software/apache-tomcat-7.0.104.tar.gz
    tds_war: ../../software/tds-5.0.0-beta6.war
    tomcat:
      home: "{{ ansible_env.HOME }}/TDS"
      jdk: "{{ ansible_env.HOME }}/TDS/jdk"
  roles:
    - role: ../../roles/tomcat
    - role: ../../roles/tds
      tds_home: "{{ tomcat.home }}/webapps/thredds"
  tasks:
    - name: Define tds.content.root.path
      lineinfile:
        create: True
        path: "{{ tomcat.home }}/bin/setenv.sh"
        mode: 0775
        line: |
          export CATALINA_OPTS="-Dtds.content.root.path={{ tomcat.home }}/content"
