- name: Start httpd
  hosts: lbs
  tasks:
    - name: Start ntpd
      service: name=ntpd state=started

    - name: Start filebeat
      service: name=filebeat state=started

    - name: Start httpd
      service: name=httpd state=started

    - name: Start CoG
      command: /etc/cog-wsgi-8889/apachectl start
      register: result
      changed_when: '"already running" not in result.stdout'

    - name: Start postgres
      service: name=postgresql state=started

- name: Start ESGF tomcat
  hosts: servers
  tasks:
    - name: Start tomcat
      shell: "nohup {{ tomcats.esgf.home }}/bin/startup.sh"
      args:
        creates: "{{ tomcats.esgf.home }}/logs/catalina.pid"
      environment:
        CATALINA_BASE: "{{ tomcats.esgf.home }}"
