- name: Start tomcats
  hosts: servers
  tasks:
    - name: Start tomcat
      shell: "nohup {{ tomcats[item].home }}/bin/startup.sh"
      args:
        creates: "{{ tomcats[item].home }}/logs/catalina.pid"
      environment:
        CATALINA_BASE: "{{ tomcats[item].home }}"
      with_items: [ "esgf" ]
