- name: Start httpd
  hosts: lbs
  tasks:
    - name: Start ntpd
      service: name=ntpd state=started

    - name: Start filebeat
      service: name=filebeat state=started

    - name: Start httpd
      service: name=httpd state=started

    - name: Start tomcat
      shell: /usr/local/tomcat/bin/startup.sh

        #    - name: Start CoG
        #      command: /etc/cog-wsgi-8889/apachectl start
        #      register: result
        #      changed_when: '"already running" not in result.stdout'
