- name: Start tomcats
  hosts: servers
  vars_files:
    - ../secrets.yml
  tasks:
    - name: Start tomcat
      shell: "nohup {{ item.home }}/bin/startup.sh"
      args:
        creates: "{{ item.home }}/logs/catalina.pid"
      environment:
        CATALINA_BASE: "{{ item.home }}"
      with_items:
        - "{{ udg }}"
