- name: Discover gateway facts
  hosts: lb
  tasks:
    - setup:

- name: Install TDS catalogs and datasets
  hosts: servers
  vars:
    gateway: "{{ hostvars['lb']['ansible_facts']['nodename'] }}"
  vars_files:
    - secrets.yml
  tasks:
    - name: Clone repos
      run_once: True
      local_action:
        module: git
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
        version: "{{ item.version }}"
        depth: 1
      with_items:
        - { "repo": "git@gitlab.com:zequihg50/tds5-content.git", "version": "master", "dest": "tds5-content" }
        - { "repo": "git@gitlab.com:SCDS/tds-content.git", "version": "lustre", "dest": "tds-content" }

    - name: Synchronize tds-content
      synchronize: src=tds-content/ dest={{ tomcats.udg.home }}/content/thredds

    - name: Synchronize tds5-content
      synchronize: src=tds5-content/ dest={{ tomcats.tds5.home }}/content/thredds

    - name: Reinit catalogs
      uri:
        url: https://{{ gateway }}/thredds/admin/{{ ansible_hostname }}/debug?Catalogs/reinit
        validate_certs: false
        user: "{{ tds.user }}"
        password: "{{ tds.password }}"
      with_items: "{{ tomcats }}"

    - name: Clear caches
      uri:
        url: https://{{ gateway }}/thredds/admin/{{ ansible_hostname }}/debug?Caches/clearCaches
        validate_certs: false
        user: "{{ tds.user }}"
        password: "{{ tds.password }}"
      with_items: "{{ tomcats }}"
