- name: Discover gateway facts
  hosts: lb
  tasks:
    - setup:

- name: Install TDS catalogs and datasets
  hosts: servers
  vars:
    gateway: "{{ hostvars['lb']['ansible_facts']['nodename'] }}"
  vars_files:
    - secrets.yml
  tasks:
    - name: Clone repos
      run_once: True
      local_action:
        module: git
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
        version: "{{ item.version }}"
        depth: 1
      with_items:
        - { "repo": "git@gitlab.com:SCDS/tds-content.git", "version": "master", "dest": "tds-content" }

    - name: Create content directories
      file: state=directory dest={{ item.home }}/content/thredds
      with_items:
        - "{{ udg }}"

    - name: Synchronize tds-content
      synchronize: src=tds-content/ dest={{ udg.home }}/content/thredds

    - name: Reinit catalogs
      uri:
        url: https://{{ gateway }}/thredds/admin/{{ ansible_hostname }}/debug?Catalogs/reinit
        validate_certs: false
        user: "{{ secrets.tds.user }}"
        password: "{{ secrets.tds.password }}"

    - name: Clear caches
      uri:
        url: https://{{ gateway }}/thredds/admin/{{ ansible_hostname }}/debug?Caches/clearCaches
        validate_certs: false
        user: "{{ secrets.tds.user }}"
        password: "{{ secrets.tds.password }}"
