- name: Discover gateway facts
  hosts: gateways
  tasks:
    - setup:

- name: Install TDS catalogs and datasets
  hosts: servers
  serial: 1
  ignore_errors: True
  vars:
    gateway: "{{ hostvars['gateway']['ansible_facts']['nodename'] }}"
  vars_files:
    - secrets.yml
  tasks:
    - name: Create content directories
      file: state=directory dest={{ item.home }}/content/thredds
      with_items: "{{ workers }}"

    - name: Clone repos
      git:
        #repo: "{{ item.repo }}"
        repo: "git@gitlab.com:SCDS/data-management/tds-content.git"
        dest: "{{ item.home }}/content/thredds"
        version: devel
        depth: 1
        executable: /lustre/gmeteo/WORK/zequi/miniconda3/bin/git
      #with_items:
      #  - { "repo": "git@gitlab.com:SCDS/tds-content.git", "version": "devel", "dest": "{{ udg.home }}/content/thredds" }
      with_items: "{{ workers }}"

    - name: Reinit catalogs
      uri:
        url: https://{{ gateway }}/thredds/admin/{{ ansible_hostname }}/debug?Catalogs/reinit
        validate_certs: false
        user: "{{ secrets.tds.user }}"
        password: "{{ secrets.tds.password }}"

    - name: Clear caches
      uri:
        url: https://{{ gateway }}/thredds/admin/{{ ansible_hostname }}/debug?Caches/clearCaches
        validate_certs: false
        user: "{{ secrets.tds.user }}"
        password: "{{ secrets.tds.password }}"
