- name: Install TDS catalogs and datasets
  hosts: servers
  vars_files:
    - secrets.yml
  tasks:
    - name: Clone tds-content repository
      run_once: True
      local_action:
        module: git
        repo: git@gitlab.com:scds/tds-content.git
        dest: tds-content
        version: master
      tags: caches

    - name: Synchronize tds-content
      run_once: True
      synchronize: src={{ tds_content }} dest={{ root }}
      tags: caches

    - name: Find directory catalogs
      find: paths={{ root }}/tds-content recurse=no file_type=any
      register: catalog_result

    - name: Symlink tds-content
      file:
        state: link
        src: "{{ item.1.path }}"
        path: "{{ item.0.base }}/content/thredds/{{ item.1.path|basename }}"
      with_nested:
        - "{{ tomcats }}"
        - "{{ catalog_result.files }}"

    - name: Set catalog and dataset permissions
      file: path={{ root }}/{{ item }} mode=u=rwX,g=rwX,o=rX recurse=yes
      with_items: [catalogs, public]
      run_once: yes

    - name: Fix TDS5 catalogs and datasets (remove tabs)
      shell: find catalogs public -type f -print0 | xargs -0 -n1 | grep -v svn | xargs -n1 perl -pi -e 's/(".*?)\t+"/\1"/g'
      args:
        chdir: "{{ item.base }}/content/thredds"
      with_items: "{{ tomcats }}"
      run_once: yes

    - name: Clear caches
      uri:
        url: "{{ item }}"
        validate_certs: false
        user: "{{ tds.user }}"
        password: "{{ tds.password }}"
      with_items:
        - https://{{ inventory_hostname }}:9443/thredds/admin/debug?Catalogs/reinit
        - https://{{ inventory_hostname }}:9443/thredds/admin/debug?Caches/clearCaches
      tags: caches
