- name: Install TDS catalogs and datasets
  hosts: servers
  vars_files:
    - secrets.yml
  tasks:
    - name: Clone tds-content repository
      run_once: True
      local_action:
        module: git
        repo: git@gitlab.com:scds/tds-content.git
        dest: tds-content
        version: spock

    - name: Synchronize tds-content
      synchronize: src=tds-content/ dest={{ tomcat_bases }}/{{ item.name }}/content/thredds
      with_items: "{{ tomcats }}"

    - name: Set catalog and dataset permissions
      file: path={{ root }}/{{ item }} mode=u=rwX,g=rwX,o=rX recurse=yes
      with_items: [catalogs, public]
      run_once: yes

    - name: Copy root catalog
      copy: src=catalog.xml dest={{ tomcat_bases }}/{{ item.name }}/content/thredds/catalog.xml
      with_items: "{{ tomcats }}"

    - name: Fix TDS5 catalogs and datasets (remove tabs)
      shell: find catalogs public -type f -print0 | xargs -0 -n1 | grep -v svn | xargs -n1 perl -pi -e 's/(".*?)\t+"/\1"/g'
      args:
        chdir: "{{ tomcat_bases }}/{{ item.name }}/content/thredds"
      with_items: "{{ tomcats }}"

    - name: Copy root catalog
      copy: src=catalog.xml dest={{ tomcat_bases }}/{{ item.name }}/content/thredds/catalog.xml
      with_items: "{{ tomcats }}"

    - name: Copy catalogs
      synchronize: src=catalogs/ dest={{ tomcat_bases }}/{{ item.name }}/content/thredds/catalogs
      with_items: "{{ tomcats }}"

    - name: Synchronize datasets
      synchronize: src=ncmls/ dest={{ tomcat_bases }}/{{ item.name }}/content/thredds/public
      with_items: "{{ tomcats }}"

    - name: Refresh catalogs
      command: curl -L --insecure -u '{{ tds.user }}:{{ tds.password }}' {{ url }}
      vars:
        url: https://{{ inventory_hostname }}:8443/tds5/admin/debug?Catalogs/reinit

    - name: Clear caches
      uri:
        url: "{{ item }}"
        validate_certs: false
        user: "{{ tds.user }}"
        password: "{{ tds.password }}"
      with_items:
        - https://{{ inventory_hostname }}:9443/thredds/admin/debug?Catalogs/reinit
        - https://{{ inventory_hostname }}:9443/thredds/admin/debug?Caches/clearCaches
      tags: caches
