- name: Install TDS catalogs and datasets
  hosts: servers
  vars_files:
    - secrets.yml
  tasks:
    - name: Create directory for TDS5 data
      file: state=directory path={{ tomcat_bases }}/{{ item.name }}/content/thredds
      with_items: "{{ tomcats }}"

    - name: Checkout TDS catalogs
      subversion:
        dest: "{{ root }}/catalogs"
        repo: https://meteo.unican.es/svn/repos/sistemas/services/TDS5/tomcat/content/thredds/catalogs/
        username: "{{ svn.username }}"
        password: "{{ svn.password }}"
        force: yes
        in_place: yes
      run_once: yes

    - name: Checkout TDS datasets
      subversion:
        dest: "{{ root }}/public"
        repo: https://meteo.unican.es/svn/repos/sistemas/services/TDS5/tomcat/content/thredds/public
        username: "{{ svn.username }}"
        password: "{{ svn.password }}"
        force: yes
        in_place: yes
      run_once: yes

    - name: Set catalog and dataset permissions
      file: path={{ root }}/{{ item }} mode=u=rwX,g=rwX,o=rX recurse=yes
      with_items: [catalogs, public]
      run_once: yes

    - name: Copy root catalog
      copy: src=catalog.xml dest={{ tomcat_bases }}/{{ item.name }}/content/thredds/catalog.xml
      with_items: "{{ tomcats }}"

    - name: Fix TDS5 catalogs and datasets (remove tabs)
      shell: find catalogs public -type f -print0 | xargs -0 -n1 | grep -v svn | xargs -n1 perl -pi -e 's/(".*?)\t+"/\1"/g'
      args:
        chdir: "{{ tomcat_bases }}/{{ item.name }}/content/thredds"
      with_items: "{{ tomcats }}"
      run_once: yes

    - name: Clear caches
      uri:
        url: "{{ item }}"
        validate_certs: false
        user: "{{ tds.user }}"
        password: "{{ tds.password }}"
      with_items:
        - https://{{ inventory_hostname }}:9443/{{ tds_context }}/admin/debug?Catalogs/reinit
        - https://{{ inventory_hostname }}:9443/{{ tds_context }}/admin/debug?Caches/clearCaches
