- name: Install TDS catalogs and datasets
  hosts: servers
  vars_files:
    - secrets.yml
  tasks:
    - name: Create directory for TDS5 data
      file: state=directory path={{ tomcat_bases }}/{{ item.name }}/content/thredds
      with_items: "{{ tomcats }}"

    - name: Synchronize TDS5 catalogs
      synchronize: >
        src=tds5/catalogs
        dest={{ tomcat_bases }}/{{ item.name }}/content/thredds
      with_items: "{{ tomcats }}"

    - name: Synchronize TDS5 datasets
      synchronize: >
        src=tds5/public/
        dest={{ tomcat_bases }}/{{ item.name }}/content/thredds/public/
      with_items: "{{ tomcats }}"

    - name: Fix TDS5 catalogs and datasets (remove tabs)
      shell: find catalogs public -type f -print0 | xargs -0 -n1 | grep -v svn | xargs -n1 perl -pi -e 's/(".*?)\t+"/\1"/g'
      args:
        chdir: "{{ tomcat_bases }}/{{ item.name }}/content/thredds"
      with_items: "{{ tomcats }}"

    - name: Copy root catalog
      copy: src=catalog.xml dest={{ tomcat_bases }}/{{ item.name }}/content/thredds/catalog.xml
      with_items: "{{ tomcats }}"

    - name: Copy catalogs
      synchronize: src=catalogs/ dest={{ tomcat_bases }}/{{ item.name }}/content/thredds/catalogs
      with_items: "{{ tomcats }}"

    - name: Synchronize datasets
      synchronize: src=ncmls/ dest={{ tomcat_bases }}/{{ item.name }}/content/thredds/public
      with_items: "{{ tomcats }}"

    - name: Clear caches
      uri:
        url: "{{ item }}"
        validate_certs: false
        user: "{{ tds.user }}"
        password: "{{ tds.password }}"
      with_items:
        - https://{{ inventory_hostname }}:9443/{{ tds_context }}/admin/debug?Catalogs/reinit
        - https://{{ inventory_hostname }}:9443/{{ tds_context }}/admin/debug?Caches/clearCaches
