- name: Install derbydb server
  hosts: databases
  vars:
    derby_tgz: db-derby-10.14.2.0-bin.tar.gz
  tasks:
    - name: Create {{ derby_home }} directory
      file: state=directory path={{ derby_home }}

    - name: Unarchive derbydb
      unarchive:
        src: ../../software/{{ derby_tgz }}
        dest: "{{ derby_home }}"
        extra_opts: --strip-components=1

    - name: Template derby.properties
      template: src=templates/derby.properties.j2 dest={{ derby_home }}/derby.properties

