- name: ATLAS development TDS
  hosts: wn023
  vars:
    jdk_home: /oceano/gmeteo/WORK/PROYECTOS/ATLAS/tds/jdk
    tomcat_home: /oceano/gmeteo/WORK/PROYECTOS/ATLAS/tds
    tds_home: /oceano/gmeteo/WORK/PROYECTOS/ATLAS/tds/webapps/thredds
    id: atlas
    http: 7000
    ajp: 7002
    shutdown: 7003
  roles:
    - role: devel

- name: C3s34d development TDS
  hosts: wn023
  vars:
    jdk_home: /oceano/gmeteo/WORK/PROYECTOS/2020_C3S_34d/tds/jdk
    tomcat_home: /oceano/gmeteo/WORK/PROYECTOS/2020_C3S_34d/tds
    tds_home: /oceano/gmeteo/WORK/PROYECTOS/2020_C3S_34d/tds/webapps/thredds
    id: c3s34d
    http: 7005
    ajp: 7007
    shutdown: 7008
  roles:
    - role: devel
