- name: Install gateway
  hosts: lb
  vars:
    hostcert: /etc/pki/tls/certs/hostcert.pem
    hostkey: /etc/pki/tls/private/hostkey.pem
  tasks:
    - name: Install httpd
      yum: name=httpd,mod_ssl state=present

    - name: Copy httpd conf
      copy: src=files/httpd.conf dest=/etc/httpd/conf/httpd.conf

    - name: Copy httpd ssl conf
      copy: src=files/httpd.ssl.conf dest=/etc/httpd/conf/httpd.ssl.conf

    - name: Template modproxy.conf
      template: src=templates/modproxy.conf.j2 dest={{ modproxy_conf }}

    - name: Add tds5 proxy
      blockinfile:
        path: "{{ modproxy_conf }}"
        marker: "# {mark} TDS5"
        insertbefore: ProxyPass "/thredds"
        block: "{{ tds5_paths }}"

    - name: Add additional reverse proxies to {{ modproxy_conf }}
      blockinfile:
        path: "{{ modproxy_conf }}"
        marker: "# {mark} Additional reverse proxies"
        block: |
          ProxyPass /work http://ui.macc.unican.es/work
          ProxyPassReverse /work http://ui.macc.unican.es/work
