- name: Install tomcats
  hosts: servers
  vars:
    tomcat_ssl_keystoreFile: "{{ tomcat_home }}/server.p12"
    tomcat_ssl_keystorePass: coches1
  vars_files:
    - secrets.yml
  tasks:
# Tomcats
    - name: Install tomcats
      include_role:
        name: tomcat
      with_items: "{{ tomcats }}"
      loop_control:
        loop_var: tomcat

    - name: Copy keystore
      copy: src=../../server.p12 dest={{ tomcat_ssl_keystoreFile }}

    - name: Unarchive derbydb client
      unarchive:
        src: "{{ derby_tgz }}"
        dest: "{{ tomcat_home }}/lib"
        exclude:
          - derby.war
          - README.htm
        extra_opts:
          - --strip-components=2

    - name: Template setenv.sh
      template: src=templates/setenv.sh.j2 dest={{ item.base }}/bin/setenv.sh
      with_items: "{{ tomcats }}"

    - name: Template server.xml
      template: src=templates/server.xml.j2 dest={{ item.base }}/conf/server.xml
      with_items: "{{ tomcats }}"

# TDS
    - name: Deploy TDSs
      include_role:
        name: tds
      vars:
        tds_home: "{{ item.base }}/webapps/thredds"
        tds_sslPort: 443
        tds_useSSL: True
      with_items: "{{ tomcats }}"

    - name: Create content/thredds
      file: state=directory path={{ item.base }}/content/thredds
      with_items: "{{ tomcats }}"

    - name: Create common catalog and ncml directories
      file: state=directory path={{ root }}/{{ item }} mode=0775
      with_items: [catalogs, public]

    - name: Copy threddsConfig.xml
      copy: src=files/threddsConfig.xml dest={{ item.base }}/content/thredds/threddsConfig.xml
      with_items: "{{ tomcats }}"

    - name: Clone tds-content repository
      run_once: True
      local_action:
        module: git
        repo: git@gitlab.com:scds/tds-content.git
        dest: tds-content

    - name: Synchronize tds-content
      run_once: True
      synchronize: src=tds-content dest={{ root }}

    - name: Find directory catalogs
      find: paths={{ root }}/tds-content recurse=no file_type=any
      register: catalog_result

    - name: Symlink tds-content
      file:
        state: link
        src: "{{ item.1.path }}"
        path: "{{ item.0.base }}/content/thredds/{{ item.1.path|basename }}"
      with_nested:
        - "{{ tomcats }}"
        - "{{ catalog_result.files }}"

# Melody
    - name: Install jrobin
      copy: src={{ jrobin_jar }} dest={{ item.base }}/webapps/thredds/WEB-INF/lib/
      with_items: "{{ tomcats }}"

    - name: Install java melody
      copy: src={{ melody_jar }} dest={{ item.base }}/webapps/thredds/WEB-INF/lib/
      with_items: "{{ tomcats }}"

# TAP
    - name: Create tap directory
      file: state=directory path={{ item.base }}/webapps/udg-tap
      with_items: "{{ tomcats }}"

    - name: Unarchive tap
      unarchive: src=../../software/udg-tap.war dest={{ item.base }}/webapps/udg-tap
      with_items: "{{ tomcats }}"

    - name: Template tap properties
      template: >
        src=templates/tap.properties.j2
        dest={{ item.base }}/webapps/udg-tap/WEB-INF/classes/global_variables.properties
      with_items: "{{ tomcats }}"

    - name: Copy context.xml
      copy: src=files/context.xml dest={{ item.base }}/conf/context.xml
      with_items: "{{ tomcats }}"

    - name: Add <absolute-ordering/> to web.xml
      lineinfile:
        path: "{{ item.base }}/webapps/udg-tap/WEB-INF/web.xml"
        insertbefore: <display-name>
        line: <absolute-ordering/>
      with_items: "{{ tomcats }}"

- name: Install derbydb
  hosts: databases
  vars:
    derby_tgz: db-derby-10.14.2.0-bin.tar.gz
  tasks:
    - name: Create {{ derby_home }} directory
      file: state=directory path={{ derby_home }}

    - name: Unarchive derbydb
      unarchive: >
        src=../../software/{{ derby_tgz }}
        dest={{ derby_home }}
        extra_opts=--strip-components=1

    - name: Template derby.properties
      template: src=templates/derby.properties.j2 dest={{ derby_home }}/derby.properties

- name: Install load balancer
  hosts: lb
  vars:
    hostcert: /etc/pki/tls/certs/hostcert.pem
    hostkey: /etc/pki/tls/private/hostkey.pem
    clusters: # modproxy requires order
      - name: circulation-types-test-devel
        urls:
          - /thredds/catalog/devel/circulation-types-test
          - /thredds/dodsC/devel/circulation-types-test
      - name: atlas-devel
        urls:
          - /thredds/catalog/devel/atlas
          - /thredds/dodsC/devel/atlas
      - name: c3s34d-devel
        urls:
          - /thredds/catalog/devel/c3s34d
          - /thredds/dodsC/devel/c3s34d
      - name: default
        urls:
          - /thredds
          - /udg-tap
  tasks:
    - name: Install httpd
      yum: name=httpd,mod_ssl state=present

    - name: Copy httpd conf
      copy: src=files/httpd.conf dest=/etc/httpd/conf/httpd.conf
      tags: update-workers

    - name: Template modproxy.conf
      template: src=templates/modproxy.conf.j2 dest={{ modproxy_conf }}
      tags: update-workers

    - name: Add additional reverse proxies to {{ modproxy_conf }}
      blockinfile:
        path: "{{ modproxy_conf }}"
        marker: "# {mark} Additional reverse proxies"
        block: |
          ProxyPass /work http://ui.macc.unican.es/work
          ProxyPassReverse /work http://ui.macc.unican.es/work
      tags: update-workers

- name: Install production workers
  hosts: servers
  serial: True
  tags: update-workers
  roles:
    - role: worker

- name: Install development TDSs
  hosts: wn023
  tasks:
    - name: Install development TDSs
      include_role:
        name: devel
      with_items: "{{ devels }}"
      loop_control:
        loop_var: tomcat
      tags: devels, update-workers
