- name: Start httpd
  hosts: lbs
  tags: update-workers
  tasks:
    - name: Start httpd
      service: name=httpd state=started

- name: Start tomcats
  hosts: servers
  tasks:
    - name: Start tomcats
      shell: "nohup {{ item.home }}/bin/startup.sh"
      args:
        creates: "{{ item.base }}/logs/catalina.pid"
      environment:
        CATALINA_BASE: "{{ item.base }}"
      with_items: "{{ tomcats }}"

- name: Start database
  hosts: databases
  tasks:
    - command: nohup bin/startNetworkServer &
      args:
        chdir: "{{ derby_home }}"
      environment:
        DERBY_HOME: "{{ derby_home }}"
        JAVA_HOME: "{{ jdk_home }}"
