- name: Start httpd
  hosts: lbs
  tags: update-workers
  tasks:
    - name: Start ntpd
      service: name=ntpd state=started

    - name: Start filebeat
      service: name=filebeat state=started

    - name: Start httpd
      service: name=httpd state=started

    - name: Start esgf tomcat
      include_tasks:
        file: restart.yml
        apply:
          tags: start
      vars:
        tomcat: "{{ esgf }}"

- name: Start production tomcats
  hosts: servers
  serial: True
  tags:
    - start
    - tomcats
  tasks:
    - include_tasks: restart.yml
      with_items: "{{ tomcats }}"
      loop_control:
        loop_var: tomcat

- name: Start database
  hosts: databases
  tags:
    - databases
    - start
  tasks:
    - command: nohup bin/startNetworkServer &
      args:
        chdir: "{{ derby_home }}"
      environment:
        DERBY_HOME: "{{ derby_home }}"
        JAVA_HOME: "{{ jdk_home }}"
