- name: Stop httpd
  hosts: lbs
  tags: update-workers
  tasks:
    - name: Stop httpd
      service: name=httpd state=stopped

- name: Stop tomcats
  hosts: servers
  tags: tomcats
  tasks:
    - name: Import stop tasks
      import_tasks: stop/tomcats.yml

- name: Stop database
  hosts: databases
  tags: databases
  tasks:
    - command: bin/stopNetworkServer
      args:
        chdir: "{{ derby_home }}"
      environment:
        DERBY_HOME: "{{ derby_home }}"
        JAVA_HOME: "{{ jdk_home }}"
      ignore_errors: True
