# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.ssh.insert_key = false
  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.define "gateway" do |gateway|
    gateway.vm.box = "centos/7"
    gateway.vm.hostname = "gateway"
    gateway.vm.network "private_network", ip: "192.168.56.10"
    gateway.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end
    gateway.vm.provision "shell", inline: <<-SHELL
      mkdir -p /root/.ssh
      chmod 700 /root/.ssh
      cp /home/vagrant/.ssh/authorized_keys /root/.ssh/authorized_keys
      chmod 700 /root/.ssh/authorized_keys

      /usr/sbin/setsebool -P httpd_can_network_connect 1
    SHELL
  end

  config.vm.define "server1" do |server1|
    server1.vm.box = "centos/7"
    server1.vm.hostname = "server1"
    server1.vm.network "private_network", ip: "192.168.56.11"
    server1.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end
  end

  config.vm.define "server2" do |server2|
    server2.vm.box = "centos/7"
    server2.vm.hostname = "server2"
    server2.vm.network "private_network", ip: "192.168.56.12"
    server2.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end
  end

#  config.vm.provision "ansible" do |ansible|
#    ansible.groups = {
#      "gateways" => ["gateway"],
#      "servers" => ["server1","server2"],
#    }
#    ansible.playbook = "provision.yml"
#  end

end
