- name: Set up gateway
  hosts: gateway
  tasks:
    - name: Template modproxy.conf
      template: src=templates/modproxy.conf.j2 dest={{ modproxy_conf }}

- name: UDG workers
  hosts: servers
  serial: 1 # multiple hosts writing to the gateway
  vars_files:
    - secrets.yml
  tasks:
    - name: Add balancers to reverse proxy
      blockinfile:
        path: "{{ modproxy_conf }}"
        insertafter: "# balancers"
        marker: "# {mark} balancer {{ item.balancer }}"
        block: | 
          <Proxy "balancer://{{ item.balancer }}">
          ProxySet stickysession=JSESSIONID
          </Proxy>
      delegate_to: gateway
      with_items: "{{ workers }}"

    - name: Add workers to balancers
      lineinfile:
        path: "{{ modproxy_conf }}"
        insertafter: '<Proxy "balancer://{{ item.balancer }}">'
        line: > 
          BalancerMember "ajp://{{ udg_ip|default(ansible_all_ipv4_addresses[0]) }}:{{ item.ajp }}" loadfactor=1 route={{ ansible_hostname }}
      delegate_to: gateway
      with_items: "{{ workers }}"

    - name: Add thredds/admin workers
      delegate_to: gateway
      blockinfile:
        path: "{{ modproxy_conf }}"
        insertafter: "# udg admin"
        marker: "# udg admin {{ udg_ip|default(ansible_all_ipv4_addresses[0]) }}:{{ udg.ssl }}"
        block: |
          ProxyPass "/thredds/admin/{{ inventory_hostname }}" "https://{{ udg_ip|default(ansible_all_ipv4_addresses[0]) }}:{{ udg.ssl }}/thredds/admin"
          ProxyPassReverse "/thredds/admin/{{ inventory_hostname }}" "https://{{ udg_ip|default(ansible_all_ipv4_addresses[0]) }}:{{ udg.ssl }}/thredds/admin"

#    - lineinfile:
#        path: "{{ modproxy_conf }}"
#        insertafter: <Proxy "balancer://{{ item }}">
#        line: BalancerMember "ajp://{{ ansible_all_ipv4_addresses[0] }}:{{ tomcats[item].ajp }}" loadfactor=1 route={{ ansible_hostname }}
#      delegate_to: lb
#      with_items: [ 'udg', 'tds5' ]
#      when: 'inventory_file|basename != "spock"'
#
#    - lineinfile:
#        path: "{{ modproxy_conf }}"
#        insertafter: <Proxy "balancer://{{ item }}">
#        line: BalancerMember "ajp://{{ ansible_all_ipv4_addresses[1] }}:{{ tomcats[item].ajp }}" loadfactor=1 route={{ ansible_hostname }}
#      delegate_to: lb
#      with_items: [ 'udg', 'tds5' ]
#      when: 'inventory_file|basename == "spock"'
#

#- name: ESGF workers
#  hosts: servers
#  tasks:
#    - lineinfile:
#        path: "{{ modproxy_conf }}"
#        insertafter: <Proxy "balancer://{{ item }}">
#        line: BalancerMember "ajp://{{ ansible_all_ipv4_addresses[0] }}:{{ tomcats[item].ajp }}" loadfactor=1 route={{ ansible_hostname }}
#      delegate_to: lb
#      with_items: [ 'esgf' ]
#      when: 'inventory_file|basename != "spock"'
#
#    - lineinfile:
#        path: "{{ modproxy_conf }}"
#        insertafter: <Proxy "balancer://{{ item }}">
#        line: BalancerMember "ajp://{{ ansible_all_ipv4_addresses[1] }}:{{ tomcats[item].ajp }}" loadfactor=1 route={{ ansible_hostname }}
#      delegate_to: lb
#      with_items: [ 'esgf' ]
#      when: 'inventory_file|basename == "spock"'

- name: Restart gateway
  hosts: lb
  tasks:
    - name: Graceful restart
      command: service httpd graceful
