- name: Set up gateway
  hosts: lb
  tasks:
    - name: Template modproxy.conf
      template: src=templates/modproxy.conf.j2 dest={{ modproxy_conf }}

- name: UDG workers
  hosts: servers
  serial: 1 # multiple hosts writing to the gateway
  vars_files:
    - secrets.yml
  tasks:
    - lineinfile:
        path: "{{ modproxy_conf }}"
        insertafter: '<Proxy "balancer://{{ item.balancer }}">'
        line: > 
          BalancerMember "ajp://{{ ansible_all_ipv4_addresses[0] }}:{{ item.ajp }}" loadfactor=1 route={{ ansible_hostname }}
      delegate_to: lb
      with_items:
        - "{{ udg }}"
      when: 'inventory_file|basename != "spock"'

    - lineinfile:
        path: "{{ modproxy_conf }}"
        insertafter: <Proxy "balancer://{{ item.balancer }}">
        line: BalancerMember "ajp://{{ ansible_all_ipv4_addresses[1] }}:{{ item.ajp }}" loadfactor=1 route={{ ansible_hostname }}
      delegate_to: lb
      with_items:
        - "{{ udg }}"
      when: 'inventory_file|basename == "spock"'

#    - lineinfile:
#        path: "{{ modproxy_conf }}"
#        insertafter: <Proxy "balancer://{{ item }}">
#        line: BalancerMember "ajp://{{ ansible_all_ipv4_addresses[0] }}:{{ tomcats[item].ajp }}" loadfactor=1 route={{ ansible_hostname }}
#      delegate_to: lb
#      with_items: [ 'udg', 'tds5' ]
#      when: 'inventory_file|basename != "spock"'
#
#    - lineinfile:
#        path: "{{ modproxy_conf }}"
#        insertafter: <Proxy "balancer://{{ item }}">
#        line: BalancerMember "ajp://{{ ansible_all_ipv4_addresses[1] }}:{{ tomcats[item].ajp }}" loadfactor=1 route={{ ansible_hostname }}
#      delegate_to: lb
#      with_items: [ 'udg', 'tds5' ]
#      when: 'inventory_file|basename == "spock"'
#
#    - name: Add thredds/admin workers
#      delegate_to: lb
#      blockinfile:
#        path: "{{ modproxy_conf }}"
#        insertafter: "# udg admin"
#        marker: "# udg admin {{ ansible_all_ipv4_addresses[0] }}:{{ tomcats['udg'].ssl }}"
#        block: |
#          ProxyPass "/thredds/admin/{{ ansible_host }}" "https://{{ ansible_all_ipv4_addresses[0] }}:{{ tomcats['udg'].ssl }}/thredds/admin"
#          ProxyPassReverse "/thredds/admin/{{ ansible_host }}" "https://{{ ansible_all_ipv4_addresses[0] }}:{{ tomcats['udg'].ssl }}/thredds/admin"

#- name: ESGF workers
#  hosts: servers
#  tasks:
#    - lineinfile:
#        path: "{{ modproxy_conf }}"
#        insertafter: <Proxy "balancer://{{ item }}">
#        line: BalancerMember "ajp://{{ ansible_all_ipv4_addresses[0] }}:{{ tomcats[item].ajp }}" loadfactor=1 route={{ ansible_hostname }}
#      delegate_to: lb
#      with_items: [ 'esgf' ]
#      when: 'inventory_file|basename != "spock"'
#
#    - lineinfile:
#        path: "{{ modproxy_conf }}"
#        insertafter: <Proxy "balancer://{{ item }}">
#        line: BalancerMember "ajp://{{ ansible_all_ipv4_addresses[1] }}:{{ tomcats[item].ajp }}" loadfactor=1 route={{ ansible_hostname }}
#      delegate_to: lb
#      with_items: [ 'esgf' ]
#      when: 'inventory_file|basename == "spock"'

- name: Restart gateway
  hosts: lb
  tasks:
    - name: Graceful restart
      command: service httpd graceful
