- name: Create directories for catalina bases
  file: state=directory path={{ tomcat_bases }}/{{ tomcat.name }}

- name: Set up catalina base
  file: path={{ tomcat_bases }}/{{ tomcat.name }}/{{ item }} state=directory
  with_items: ['bin', 'conf', 'lib', 'logs', 'webapps', 'temp']

- name: Copy server.xml
  copy: >
    src={{ tomcat_home }}/conf/server.xml
    dest={{ tomcat_bases }}/{{ tomcat.name }}/conf/server.xml
    remote_src=True

- name: Copy web.xml
  copy: >
    src={{ tomcat_home }}/conf/web.xml
    dest={{ tomcat_bases }}/{{ tomcat.name }}/conf/web.xml
    remote_src=True