- name: Create directory for jdk
  file: state=directory path={{ tomcat.jdk }}

- name: Unarchive jdk in {{ tomcat.home }}
  unarchive:
    src: "{{ jdk_tgz }}"
    dest: "{{ tomcat.jdk }}"
    extra_opts: "--strip-components=1"

- name: Create catalina_home directory
  file: state=directory path={{ tomcat.home }}

- name: Unarchive tomcat in catalina_home
  unarchive:
    src: "{{ tomcat_tgz }}"
    dest: "{{ tomcat.home }}"
    extra_opts: "--strip-components=1"

# Set up catalina base
- name: Create catalina_base directory
  file: state=directory path={{ tomcat.base | default(tomcat.home) }}

- name: Create catalina_base/bin directory
  file: state=directory path={{ tomcat.base | default(tomcat.home) }}/bin

- name: Create catalina_base/conf directory
  file: state=directory path={{ tomcat.base | default(tomcat.home) }}/conf

- name: Create catalina_base/lib directory
  file: state=directory path={{ tomcat.base | default(tomcat.home) }}/lib

- name: Create catalina_base/logs directory
  file: state=directory path={{ tomcat.base | default(tomcat.home) }}/logs

- name: Create catalina_base/webapps directory
  file: state=directory path={{ tomcat.base | default(tomcat.home) }}/webapps

- name: Create catalina_base/temp directory
  file: state=directory path={{ tomcat.base | default(tomcat.home) }}/temp

# Copy catalina base files
- name: Copy server.xml
  copy:
    src: "{{ tomcat.home }}/conf/server.xml"
    dest: "{{ tomcat.base | default(tomcat.home) }}/conf/server.xml"
    remote_src: True

- name: Copy web.xml
  copy:
    src: "{{ tomcat.home }}/conf/web.xml"
    dest: "{{ tomcat.base | default(tomcat.home) }}/conf/web.xml"
    remote_src: True
