- name: Create directory for jdk
  file: state=directory path={{ jdk_home }}

- name: Unarchive jdk in {{ tomcat_home }}
  unarchive: >
    src={{ jdk_tgz }} dest={{ jdk_home }}
    extra_opts="--strip-components=1"

- name: Create {{ tomcat_home }} directory
  file: state=directory path={{ tomcat_home }}

- name: Unarchive tomcat in {{ tomcat_home }}
  unarchive: >
    src={{ tomcat_tgz }} dest={{ tomcat_home }}
    extra_opts="--strip-components=1"
