- name: Check if cluster for workder is defined
  lineinfile:
    path: "{{ modproxy_conf }}"
    line: <Proxy "balancer://{{ item.cluster }}">
  delegate_to: "{{ item.gateway }}"
  with_items: "{{ tomcats }}"
  check_mode: yes
  register: is_present

- name: Add tomcat as a modproxy worker
  blockinfile:
    path: "{{ modproxy_conf }}"
    insertafter: <Proxy "balancer://{{ item.cluster }}">
    marker: "# {mark} {{ item.cluster }}://{{ item.host }}:{{ item.ajp }}"
    block: |
      BalancerMember "ajp://{{ item.host }}:{{ item.ajp }}" {{ item.properties }}
  delegate_to: "{{ item.gateway }}"
  with_items: "{{ tomcats }}"
  when: not is_present.changed
