- name: Create downloads directory
  run_once: True
  local_action:
    module: file
    state: directory
    dest: ./downloads

- name: Create directories
  file: state=directory dest={{ item }}
  with_items:
    - "{{ solr.home }}"

- name: Solr downloads
  run_once: True
  local_action:
    module: get_url
    url: "{{ item.url }}"
    dest: ./downloads/{{ item.dest }}
  with_items:
    - { "url": "{{ solr.src }}", "dest": "{{ solr.src|basename }}" }
    - { "url": "{{ assets.base }}/solr-home.tar", "dest": "solr-home.tar" }

- name: Install solr
  unarchive:
    src: ./downloads/{{ solr.src|basename }}
    dest: "{{ solr.path|dirname }}"

- name: Install solr core
  unarchive:
    src: ./downloads/solr-home.tar
    dest: "{{ solr.home }}"
    extra_opts: [--strip-components=1]

- name: Install solr.in.sh
  template:
    src: solr.in.sh.j2
    dest: "{{ solr.path }}/bin/solr.in.sh"

#- name: Add default shards
#  include_tasks: add_shard.yml
#  loop: "{{ solr.shards }}"
#  loop_control:
#    loop_var: shard
